{
 "title": "Sample-App Metrics Dashboard",
 "tags": [
  "application",
  "sample-app",
  "canary"
 ],
 "refresh": "25s",
 "panels": [
  {
   "title": "Application Requests",
   "type": "graph",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{app=\"sample-app\"}[5m])) by (namespace, method, status)",
     "legendFormat": "{{namespace}} - {{method}} [{{status}}]"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{app=\"sample-app\",status=~\"5..\"}[5m])) by (namespace) / sum(rate(http_requests_total{app=\"sample-app\"}[5m])) by (namespace)",
     "legendFormat": "{{namespace}} error rate"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "x": 0, "y": 9, "w": 8, "h": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\"sample-app.*\",container=\"sample-app\"}) by (namespace)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "x": 8, "y": 9, "w": 8, "h": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"sample-app.*\",container=\"sample-app\"}[5m])) by (namespace)"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "x": 16, "y": 9, "w": 8, "h": 3 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds"
    }
   ]
  }
 ]
}